### ISSUE TITLE
Security alerty for moneals

### ISSUE THREAD

**Issue by dustball** [moneals/whois-raw#6]
Do you run domination.io?

Is your username moneals?

Does your password start with "2bm"? Either for rapidAPI, amazon, your socks proxy, or something?

I am a friendly developer, letting you know about a potential security leak.

**Comment by moneals** [comment]
Hey - it does actually - where did you spot that?

Thanks btw for reaching out.

**Comment by dustball** [comment]
E-mail me at brian (dot) klug (at) gmail?  Don't want to leak it here on github.

**Comment by moneals** [comment]
Closing this as it was related to a separate project.
